export const TODO_TITLE_REQUIRED = 'TODO_TITLE_REQUIRED'
export const ADD_TODO = 'ADD_TO_DO'
export const FETCH_TODO_FROM_API = 'FETCH_TODO_FROM_API';
export const FETCHED_TODO_FROM_API = 'FETCHED_TODO_FROM_API';
export const COUNT_TOTAL_USERS = 'COUNT_TOTAL_USERS';
export const SET_TOTAL_USERS = 'SET_TOTAL_USERS'